apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "test-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: "httpbin:80"
      number: 80
      protocol: HTTP
  - hosts:
    - "*"
    port:
      name: "orion:1026"
      number: 1026
      protocol: HTTP

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - "test-gateway"
  hosts:
  - "*"
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
      weight: 100

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orion
spec:
  gateways:
  - "test-gateway"
  hosts:
  - "*"
  http:
  - match:
    - port: 1026
    route:
    - destination:
        host: orion
        port:
          number: 1026
      weight: 100
